spring.config.import=optional:dotenv:./.env

spring.application.name=ticketjo-backend
# ========== PostgreSQL DB Config ==========
spring.datasource.url=${JDBC_DATABASE_URL}
#spring.datasource.url=jdbc:postgresql://localhost:5432/ticketjo_bd
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Swagger UI path (facultatif mais pratique)
springdoc.swagger-ui.path=/swagger-ui.html

# Permet d'accéder à l'UI de Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ========== Flyway Config ==========
spring.flyway.locations=classpath:db/migration

## ========== Profil en mode dev ==========
spring.profiles.active=dev
spring.jpa.open-in-view=false

#Configuration de stripe${}
stripe.api-key=${STRIPE_API_KEY}

#=========== clé pour le JWT ==============
jwt.secret=${JWT_SECRET}
stripe.webhook-secret=${STRIPE.WEBHOOK-SECRET}

# ----------------- Google OAuth2 -----------------
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=openid,profile,email


