spring.application.name=ticketjo-backend
# ========== PostgreSQL DB Config ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketjo_bd
spring.datasource.username=fatou
spring.datasource.password=fatou123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#Pour montrer que je suis en mode dev
spring.profiles.active=dev
spring.jpa.open-in-view=false

#Configuration de stripe
stripe.secret.key=pk_test_51RDeAhRhNkRLZJCYZXKgDbG4Sw7bXY9r1P67xp5lkHToIm5Z9JDEcWhmhoSS44FBrkBtCuqWFjx61Gv5bpWGOZxu00RYQghZ1W

# cl� pour le JWT

jwt.secret=tonSuperSecretQuiDoitResterSecret123456