-- V1__init.sql

CREATE TABLE role (
    idRole BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomRole VARCHAR(255),
    descriptionRole VARCHAR(255)
);

CREATE TABLE utilisateur (
    idUtilisateur BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom             VARCHAR(255),
    prenom          VARCHAR(255),
    email           VARCHAR(255),
    motDePasse      VARCHAR(255),
    telephone       VARCHAR(255),
    adresse         VARCHAR(255),
    dateInscription DATE,
    cleUtilisateur  VARCHAR(255),
    roleId          BIGINT,
    CONSTRAINT fk_utilisateur_role
        FOREIGN KEY (roleId)
        REFERENCES role(idRole)
);

CREATE TABLE evenement (
    idEvenement         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomEvenement        VARCHAR(255),
    dateEvenement       DATE,
    lieuEvenement       VARCHAR(255),
    discipline          VARCHAR(255),
    descriptionEvenement VARCHAR(255),
    imageUrl            VARCHAR(255)
);

CREATE TABLE commande (
    idCommande     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dateCommande   DATE,
    statutCommande VARCHAR(255),
    totalCommande  DOUBLE PRECISION,
    utilisateurId  BIGINT,
    CONSTRAINT fk_commande_utilisateur
        FOREIGN KEY (utilisateurId)
        REFERENCES utilisateur(idUtilisateur)
);

CREATE TABLE paiement (
    idPaiement      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datePaiement    DATE,
    methodePaiement VARCHAR(255),
    montantPaiement DOUBLE PRECISION,
    statut          VARCHAR(255),
    commandeId      BIGINT,
    CONSTRAINT fk_paiement_commande
        FOREIGN KEY (commandeId)
        REFERENCES commande(idCommande)
);

CREATE TABLE ticket (
    idTicket     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cleTicket    VARCHAR(255),
    prixTicket   DOUBLE PRECISION,
    statutTicket VARCHAR(255),
    typeTicket   VARCHAR(255),
    qrCode       VARCHAR(255),
    imageTicket  VARCHAR(255),
    stock        INTEGER,
    commandeId   BIGINT,
    evenementId  BIGINT,
    CONSTRAINT fk_ticket_commande
        FOREIGN KEY (commandeId)
        REFERENCES commande(idCommande),
    CONSTRAINT fk_ticket_evenement
        FOREIGN KEY (evenementId)
        REFERENCES evenement(idEvenement)
);
