-- Ajout de la colonne utilisateurId dans paiement
ALTER TABLE paiement
ADD COLUMN IF NOT EXISTS utilisateurId BIGINT;

ALTER TABLE paiement
ADD CONSTRAINT fk_paiement_utilisateur
FOREIGN KEY (utilisateurId)
REFERENCES utilisateur(idUtilisateur);

-- Création de la table ticket_vendu
CREATE TABLE ticket_vendu (
    idTicketVendu       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cleTicket           VARCHAR(255) NOT NULL UNIQUE,
    qrCode              VARCHAR(255) NOT NULL,
    statutTicket        VARCHAR(255) NOT NULL, -- UTILISÉ ou NON_UTILISÉ
    dateAchat           TIMESTAMP NOT NULL,
    idUtilisateur       BIGINT NOT NULL,
    idCommande          BIGINT NOT NULL,
    idTicket            BIGINT NOT NULL,
    typeTicket          VARCHAR(255) NOT NULL,
    prixTicket          DOUBLE PRECISION NOT NULL,
    imageTicket         VARCHAR(255),

    CONSTRAINT fk_ticketvendu_utilisateur FOREIGN KEY (idUtilisateur)
        REFERENCES utilisateur(idUtilisateur),
    CONSTRAINT fk_ticketvendu_commande FOREIGN KEY (idCommande)
        REFERENCES commande(idCommande),
    CONSTRAINT fk_ticketvendu_ticket FOREIGN KEY (idTicket)
        REFERENCES ticket(idTicket)
);
