CREATE TABLE ticketCommande (
    idTicketCommande BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commandeId       BIGINT NOT NULL,
    idTicket         BIGINT NOT NULL,
    quantite         INT NOT NULL,

    CONSTRAINT fkTicketCommande_commande
        FOREIGN KEY (commandeId)
        REFERENCES commande(idCommande),

    CONSTRAINT fkTicketCommande_ticket
        FOREIGN KEY (idTicket)
        REFERENCES ticket(idTicket)
);