-- Supprimer la table ticket avec ses dépendances (contraintes étrangères)
DROP TABLE IF EXISTS ticket CASCADE;

-- Créer la nouvelle table ticketCatalogue
CREATE TABLE ticketCatalogue (
    idTicket BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typeTicket VARCHAR(255),
    prixTicket DOUBLE PRECISION,
    stock INTEGER,
    capacite INTEGER,
    imageTicket VARCHAR(255)
);