ALTER TABLE ticketCommande
ADD COLUMN IF NOT EXISTS nom VARCHAR(255) NOT NULL;

ALTER TABLE ticketCommande
ADD COLUMN IF NOT EXISTS prenom VARCHAR(255) NOT NULL;
DROP TABLE IF EXISTS ticket_vendu;

CREATE TABLE ticket_vendu (
    idTicketVendu       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cleTicket           VARCHAR(255) NOT NULL UNIQUE,
    nom                 VARCHAR(255) NOT NULL,
    prenom              VARCHAR(255) NOT NULL,
    qrCode              VARCHAR(255) NOT NULL,
    statutTicket        VARCHAR(255) NOT NULL,
    dateAchat           TIMESTAMP NOT NULL,
    idUtilisateur       BIGINT NOT NULL,
    idCommande          BIGINT NOT NULL,
    idTicket            BIGINT NOT NULL,
    typeTicket          VARCHAR(255) NOT NULL,
    prixTicket          DOUBLE PRECISION NOT NULL,
    imageTicket         VARCHAR(255),

    CONSTRAINT fk_ticketvendu_utilisateur FOREIGN KEY (idUtilisateur)
        REFERENCES utilisateur(idUtilisateur),
    CONSTRAINT fk_ticketvendu_commande FOREIGN KEY (idCommande)
        REFERENCES commande(idCommande),
    CONSTRAINT fk_ticketvendu_ticket FOREIGN KEY (idTicket)
        REFERENCES ticketCatalogue(idTicket)
);